services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PORT: ${PORT}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
